=head1 NAME

cqp - The corpus query processor of the CWB (interactive version)

=head1 SYNOPSIS

B<cqp> [-eC] [-hvmpscixS] [-D I<corpus>] [-r I<registry_dir>] [-l I<data_dir>]
    [-I I<init_file>] [-M I<macro_file>] [-f I<script_file>] [-P I<pager>]
    [-W I<n>] [-L I<n>] [-R I<n>] [-b I<n>] [-d I<mode>]

=head1 DESCRIPTION

B<TODO>


=head1 OPTIONS

    -h           help
    -v           version and copyright information
    -r dir       use <dir> as default registry
    -l dir       store/load subcorpora in <dir>
    -I file      read <file> as init file
    -M file      read macro definitions from <file>
    -m           disable macro expansion
    -e           enable input line editing
    -C           enable ANSI colours (experimental)
    -f filename  execute commands from file (batch mode)
    -p           turn pager off
    -P pager     use program <pager> to display query results
    -s           auto subquery mode
    -c           child process mode
    -i           print matching ranges only (binary output)
    -W num       show <num> chars to the left & right of match
    -L num       show <num> chars to the left of match
    -R num       show <num> chars to the right of match
    -D corpus    set default corpus to <corpus>
    -b num       set hard boundary for kleene star to <num> tokens
    -S           SIG_PIPE handler toggle
    -x           insecure mode (when run SETUID)
    -d mode      activate/deactivate debug mode, where <mode> is one of: 
       [ ShowSymtab, ShowPatList, ShowEvaltree, ShowDFA, ShowCompDFA,   ]
       [ ShowGConstraints, SymtabDebug, TreeDebug, CLDebug,             ]
       [ EvalDebug, InitialMatchlistDebug, DebugSimulation,             ]
       [ VerboseParser, ParserDebug, ParseOnly, SearchDebug, MacroDebug ]
       [ ALL (activate all modes except ParseOnly)                      ]

=over 4

=item B<TODO>

=back


=head1 COPYRIGHT

=over 4

=item
B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

=item
Copyright (C) 1993-2006 by IMS, University of Stuttgart

=item
Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

=back

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

