=head1 NAME

cwb-s-decode - Decode single structural annotation of CWB corpus

=head1 SYNOPSIS

B<cwb-s-decode> [I<options>] I<corpus> -S I<attribute>

=head1 DESCRIPTION

B<TODO>


=head1 OPTIONS

  -r <reg> use registry directory <reg>
  -n       do not show corpus positions
  -v       do not show annotated values
  -h       print this usage text.

=over 4

=item B<TODO>

=back


=head1 OUTPUT FORMAT

One line for each I<attribute> region in the corpus, with the following TAB-delimited fields:

=over 4

=item region start

corpus position of first token in region

=item region end

corpus position of last token in region

=item [ annotation ]

annotated string value (only if s-attribute has annotations)

=back


B<TODO>


=head1 COPYRIGHT

=over 4

=item
B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

=item
Copyright (C) 1993-2006 by IMS, University of Stuttgart

=item
Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

=back

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

