=head1 NAME

cwb-huffcode - Compress token-level annotations of CWB corpus

=head1 SYNOPSIS

B<cwb-huffcode> [-v] [-T] [-r I<registry_dir>] [-f <prefix>]
    ( -P I<attribute> | -A ) I<corpus>

=head1 DESCRIPTION

B<TODO>

Compress the token sequence of a positional attribute. Creates C<.huf>, C<.hcd>, and C<.huf.syn> files, which replace the corresponding C<.corpus> files. After running this tool successfully, the C<.corpus> files can be deleted.

B<NB:> The recommended front-end for indexing and compression is the B<cwb-make> program supplied as part of the CWB/Perl interface.


=head1 OPTIONS

  -P <att>  compress attribute <att> [default: word]
  -A        compress all positional attributes
  -r <dir>  set registry directory
  -f <file> set output file prefix (creates <file>.huf, ...)
  -v        verbose mode (shows protocol) [may be repeated]
  -T        skip validation pass ('I trust you')
  -h        this help page

=over 4

=item B<TODO>

=back


=head1 COPYRIGHT

=over 4

=item
B<IMS Open Corpus Workbench (CWB)> L<http://cwb.sourceforge.net/>

=item
Copyright (C) 1993-2006 by IMS, University of Stuttgart

=item
Copyright (C) 2007- by the respective contributers (see file F<AUTHORS>)

=back

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details
(in the file F<COPYING>, or available via WWW at
L<http://www.gnu.org/copyleft/gpl.html>).

=cut

