FROM textlab/busybox-minimal
MAINTAINER Michał Kosek <michalkk@student.iln.uio.no>

RUN ["busybox", "sh", "-c", "mkdir /corpora && chown 61054 /corpora"]
VOLUME /corpora
CMD ["busybox", "echo", "OK"]
