# ===========================================================================
# Project:   Glossa
# Copyright: ©2011 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => ["sproutcore/core_foundation", "sproutcore/datastore"],
       :theme => "sproutcore/empty_theme"

proxy '/searches', :to => 'localhost:3000'
proxy '/corpora', :to => 'localhost:3000'

