#!/bin/bash

# Note : this script will probably work on Debian too.

# run as root! su or sudo.

who=$(whoami)

if [[ "$who" != root ]]
then
  echo "This script must be run as root."
  echo "Please try again: sudo cwb-install-ubuntu"
  echo "Thanks!"
  exit
fi

apt-get install autoconf bison flex gcc libc6-dev libncurses5-dev make

./install-scripts/cwb-config-basic

make clean
make depend
make cl
make editline
make utils
make cqp

make install
