---
  port: 61054
  address: 0.0.0.0
  jruby_min_runtimes: 1
  jruby_max_runtimes: 1
  threadsafe: true
  default_servlet:
    mapping:
      - /assets/*
      - /media/*
  web_apps:
    default:
      root_dir: '.'
      context_path: <%= ENV['RAILS_RELATIVE_URL_ROOT'] %>
