#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)

require 'rails/commands/server'
module Rails
  class Server
    def default_options
      super.merge({
        :Port => 61054
      })
    end
  end
end

require 'rails/commands'
