# ===========================================================================
# Project:   Glossa
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => :sproutcore, :theme => 'sproutcore/ace'

proxy '/searches', :to => 'localhost:3000'
