# ===========================================================================
# Project:   Glossa
# Copyright: ©2010 My Company, Inc.
# ===========================================================================

# Add initial buildfile information here
config :all, :required => [:sproutcore, :ki, 'sproutcore/ace'],
  :theme => 'sproutcore/ace', :css_theme => 'ace'

proxy '/searches', :to => 'localhost:3000'
