CWB: cqp/ascii-print.h File Reference
ascii-print.h File Reference
#include <stdio.h>
#include "../cl/bitfields.h"
#include "corpmanag.h"
#include "context_descriptor.h"
#include "print-modes.h"
#include "groups.h"
Functions
char * ascii_convert_string (char *s)
Convert string function for ASCII mode.
void ascii_print_aligned_line (FILE *stream, int highlighting, char *attribute_name, char *line)
void ascii_print_corpus_header (CorpusList *cl, FILE *outfd)
void ascii_print_output (CorpusList *cl, FILE *outfd, int interactive, ContextDescriptor *cd, int first, int last)
void ascii_print_group (Group *group, int expand, FILE *fd)
char * get_colour_escape (char colour, int foreground)
Dummy function.
char * get_typeface_escape (char typeface)
Dummy function.
Variables
PrintDescriptionRecord ASCIIPrintDescriptionRecord
Print description record for ASCII print mode.
Function Documentation
char* ascii_convert_string (char * s)
Convert string function for ASCII mode.
Parameters:
s The string to convert.
Returns:
s (ie no change).
void ascii_print_aligned_line (FILE * stream, int highlighting, char * attribute_name, char * line)
References get_colour_escape(), and get_typeface_escape().
Referenced by printAlignedStrings().
void ascii_print_corpus_header (CorpusList * cl, FILE * outfd)
References CD, CHAR_CONTEXT, cl::corpus, _context_description_block::left_structure_name, _context_description_block::left_type, _context_description_block::left_width, cl::mother_name, cl::name, TCorpus::name, passwd, cl::query_corpus, cl::query_text, TCorpus::registry_name, _context_description_block::right_structure_name, _context_description_block::right_type, _context_description_block::right_width, cl::size, and WORD_CONTEXT.
Referenced by print_corpus_info_header().
void ascii_print_group (Group * group, int expand, FILE * fd)
References _grouptable::count_cells, _id_cnt_mapping::freq, Group_id2str(), _grouptable::nr_cells, pretty_print, _id_cnt_mapping::s, SEPARATOR, _grouptable::source_attribute, _id_cnt_mapping::t, and UseExternalGrouping.
Referenced by print_group().
void ascii_print_output (CorpusList * cl, FILE * outfd, int interactive, ContextDescriptor * cd, int first, int last)
References broken_pipe, GlobalPrintOptions, highlighting, _print_option_rec_::number_lines, print_concordance_line(), _context_description_block::printStructureTags, cl::size, and cl::sortidx.
Referenced by print_output().
char* get_colour_escape (char colour, int foreground)
Dummy function.
Referenced by ascii_print_aligned_line(), ascii_print_field(), and main().
char* get_typeface_escape (char typeface)
Dummy function.
Referenced by ascii_print_aligned_line(), and main().
Variable Documentation
PrintDescriptionRecord ASCIIPrintDescriptionRecord
Print description record for ASCII print mode.
Referenced by print_concordance_line(), and printAlignedStrings().