CWB: cl/compression.h File Reference
compression.h File Reference
#include "globals.h"
#include "bitio.h"
Functions
int compute_ba (int ft, int corpus_size)
{I have no idea what this does -- AH}
int read_golomb_code_bs (int b, BStream *bs)
Reads an integer from a Golomb-coded bitstream.
int read_golomb_code_bf (int b, BFile *bf)
Reads an integer from a Golomb-coded bit-file-buffer.
int write_golomb_code (int x, int b, BFile *bf)
Writes an integer to a Golomb-coded bit-file-buffer.
Function Documentation
int compute_ba (int ft, int corpus_size)
{I have no idea what this does -- AH}
Parameters:
ft ??
corpus_size ??
Returns:
??
Referenced by compress_reversed_index(), decompress_check_reversed_index(), get_positions(), and OpenPositionStream().
int read_golomb_code_bf (int b, BFile * bf)
Reads an integer from a Golomb-coded bit-file-buffer.
Parameters:
b ???
bf The bit-filem to read from.
Returns:
The integer that is read.
References BFread(), and log2.
Referenced by decompress_check_reversed_index().
int read_golomb_code_bs (int b, BStream * bs)
Reads an integer from a Golomb-coded bitstream.
Parameters:
b ???
bs The bitstream to read from.
Returns:
The integer that is read.
References BSread(), and log2.
Referenced by get_positions(), and ReadPositionStream().
int write_golomb_code (int x, int b, BFile * bf)
Writes an integer to a Golomb-coded bit-file-buffer.
Parameters:
x Integer to write
b ???
bf The bit-file to read from.
Returns:
Always 1.
References BFwrite(), BFwriteWord(), and log2.
Referenced by compress_reversed_index().