CWB: cqp/context_descriptor.h File Reference
context_descriptor.h File Reference
#include "attlist.h"
Data Structures
struct _context_description_block
Defines
#define CHAR_CONTEXT -1
#define WORD_CONTEXT -2
#define STRUC_CONTEXT -3
#define ALIGN_CONTEXT -4
Typedefs
typedef struct
_context_description_block ContextDescriptor
Functions
int verify_context_descriptor (Corpus *corpus, ContextDescriptor *cd, int remove_illegal_entries)
int initialize_context_descriptor (ContextDescriptor *cd)
int update_context_descriptor (Corpus *corpus, ContextDescriptor *cd)
ContextDescriptor * NewContextDescriptor ()
void FreeContextDescriptor (ContextDescriptor **cdp)
void PrintContextDescriptor (ContextDescriptor *cdp)
Define Documentation
#define ALIGN_CONTEXT -4
Referenced by compose_kwic_line(), print_option_value(), PrintContextDescriptor(), and verify_context_descriptor().
#define CHAR_CONTEXT -1
Referenced by ascii_print_corpus_header(), compose_kwic_line(), html_print_context(), initialize_context_descriptor(), latex_print_context(), print_option_value(), PrintContextDescriptor(), set_context_option_value(), set_default_option_values(), and sgml_print_context().
#define STRUC_CONTEXT -3
Referenced by compose_kwic_line(), html_print_context(), latex_print_context(), print_option_value(), PrintContextDescriptor(), set_context_option_value(), sgml_print_context(), and verify_context_descriptor().
#define WORD_CONTEXT -2
Referenced by ascii_print_corpus_header(), compose_kwic_line(), html_print_context(), init_align_module(), latex_print_context(), print_option_value(), PrintContextDescriptor(), set_context_option_value(), and sgml_print_context().
Typedef Documentation
typedef struct _context_description_block ContextDescriptor
Function Documentation
void FreeContextDescriptor (ContextDescriptor ** cdp)
Referenced by initialize_cl().
int initialize_context_descriptor (ContextDescriptor * cd)
References _context_description_block::alignedCorpora, _context_description_block::attributes, CHAR_CONTEXT, _context_description_block::left_structure, _context_description_block::left_structure_name, _context_description_block::left_type, _context_description_block::left_width, _context_description_block::print_cpos, _context_description_block::printStructureTags, _context_description_block::right_structure, _context_description_block::right_structure_name, _context_description_block::right_type, _context_description_block::right_width, and _context_description_block::strucAttributes.
Referenced by init_align_module(), NewContextDescriptor(), printAlignedStrings(), and set_default_option_values().
ContextDescriptor* NewContextDescriptor ()
References cl_malloc(), and initialize_context_descriptor().
void PrintContextDescriptor (ContextDescriptor * cdp)
References ALIGN_CONTEXT, _context_description_block::alignedCorpora, ascii, _context_description_block::attributes, CHAR_CONTEXT, close_stream(), _context_description_block::left_structure_name, _context_description_block::left_type, _context_description_block::left_width, open_stream(), pretty_print, _context_description_block::print_cpos, PrintAttributes(), PrintAttributesSimple(), _context_description_block::right_structure_name, _context_description_block::right_type, _context_description_block::right_width, show_targets, Redir::stream, STRUC_CONTEXT, _context_description_block::strucAttributes, and WORD_CONTEXT.
int update_context_descriptor (Corpus * corpus, ContextDescriptor * cd)
References _context_description_block::alignedCorpora, ATT_ALIGN, ATT_POS, ATT_STRUC, _context_description_block::attributes, find_attribute(), _attlist::list, _attrbuf::name, NewAttributeList(), _attrbuf::next, _context_description_block::printStructureTags, RecomputeAL(), RemoveNameFromAL(), _context_description_block::strucAttributes, and structure_has_values().
Referenced by printAlignedStrings(), and set_current_corpus().
int verify_context_descriptor (Corpus * corpus, ContextDescriptor * cd, int remove_illegal_entries)
References ALIGN_CONTEXT, _context_description_block::alignedCorpora, ATT_ALIGN, ATT_STRUC, _context_description_block::attributes, cqpmessage(), DestroyAttributeList(), find_attribute(), _context_description_block::left_structure, _context_description_block::left_structure_name, _context_description_block::left_type, _context_description_block::left_width, _attlist::list, _context_description_block::printStructureTags, RESET_LEFT_CONTEXT, RESET_RIGHT_CONTEXT, _context_description_block::right_structure, _context_description_block::right_structure_name, _context_description_block::right_type, _context_description_block::right_width, STRUC_CONTEXT, _context_description_block::strucAttributes, VerifyList(), and Warning.
Referenced by catalog_corpus().