CWB: utils/cwb-align-encode.c File Reference
cwb-align-encode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include "../cl/cl.h"
#include "../cl/storage.h"
#include "../cl/attributes.h"
Functions
void print_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
int parse_args (int ac, char *av[], int min_args)
Parses the program's commandline arguments.
int main (int argc, char *argv[])
Main function for cwb-align-encode.
Variables
char * progname = ""
Name of the program (from the shell).
int compatibility = 0
create .alg file for backward compatibility ?
char * registry_dir = NULL
CL registry directory.
int reverse = 0
encode inverse alignment?
char * data_dir = NULL
where to store encoded alignment attribute
int data_dir_from_corpus = 0
determine data directory from registry entry?
int verbose = 0
print some information about what files are created
Function Documentation
int main (int argc, char * argv[])
Main function for cwb-align-encode.
Parameters:
argc Number of command-line arguments.
argv Command-line arguments.
References af, af_is_pipe, align_name, ATT_ALIGN, ATT_POS, cl_free, cl_malloc(), cl_max_cpos, cl_new_attribute, cl_new_corpus, cl_strdup(), cl_string_canonical(), CompAlignData, compatibility, component_full_name(), CompXAlignData, corpus1, corpus1_name, corpus2, corpus2_name, data_dir, data_dir_from_corpus, IGNORE_CASE, line, NwriteInt(), parse_args(), progname, registry_dir, reverse, s1_name, s2_name, size1, size2, verbose, w1, and w2.
int parse_args (int ac, char * av[], int min_args)
Parses the program's commandline arguments.
Usage: optindex = parse_args(argc, argv, required_arguments);
Parameters:
ac The program's argc
av The program's argv
min_args Minimum number of arguments to be parsed.
Returns:
The value of optind after parsing, ie the index of the first argument in argv[]
References compatibility, data_dir, data_dir_from_corpus, print_usage(), progname, registry_dir, reverse, and verbose.
Referenced by main().
void print_usage (void)
Prints a message describing how to use the program to STDERR and then exits.
References progname.
Referenced by parse_args().
Variable Documentation
int compatibility = 0
create .alg file for backward compatibility ?
Referenced by main(), and parse_args().
char* data_dir = NULL
where to store encoded alignment attribute
Referenced by main(), and parse_args().
int data_dir_from_corpus = 0
determine data directory from registry entry?
Referenced by main(), and parse_args().
char* progname = ""
Name of the program (from the shell).
char* registry_dir = NULL
CL registry directory.
Referenced by main(), and parse_args().
int reverse = 0
encode inverse alignment?
Referenced by main(), and parse_args().
int verbose = 0
print some information about what files are created
Referenced by cwbci_parse_options(), do_alignment(), main(), parse_args(), and parse_options().