CWB: utils/cwb-s-encode.c File Reference
cwb-s-encode.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <assert.h>
#include "../cl/globals.h"
#include "../cl/endian.h"
#include "../cl/macros.h"
#include "../cl/cl.h"
#include "../cl/storage.h"
#include "../cl/lexhash.h"
Data Structures
struct Range
struct _SL
Defines
#define UMASK 0644
#define RNG_RNG "%s/%s.rng"
#define RNG_AVX "%s/%s.avx"
#define RNG_AVS "%s/%s.avs"
Typedefs
typedef struct _SL * SL
Enumerations
enum { set_none, set_any, set_regular, set_whitespace }
Functions
void SL_rewind (void)
SL SL_next (void)
SL SL_seek (int cpos)
SL SL_insert_after_point (int start, int end, char *annot)
void SL_delete (SL item)
void SL_insert (int start, int end, char *annot)
int parse_line (char *line, int *start, int *end, char **annot)
char * check_set (char *annot)
void usage ()
void declare_range (char *name, char *directory, int store_values)
void open_range (void)
void close_range (void)
void parse_options (int argc, char **argv)
Parses program options and sets global variables.
void write_region_to_disk (int start, int end, char *annot)
int main (int argc, char **argv)
Main function for cwb-s-encode.
Variables
int debug = 0
int silent = 0
int strip_blanks_in_values = 0
int set_syntax_strict = 0
int in_memory = 0
int add_to_existing = 0
FILE * text_fd = NULL
Corpus * corpus = NULL
int line = 0
enum { ... } set_att
Range range
char * progname = NULL
SL StructureList = NULL
SL SL_Point = NULL
cl_lexhash LH = NULL
Define Documentation
#define RNG_AVS "%s/%s.avs"
Referenced by open_range().
#define RNG_AVX "%s/%s.avx"
Referenced by open_range().
#define RNG_RNG "%s/%s.rng"
Referenced by open_range().
#define UMASK 0644
Typedef Documentation
typedef struct _SL * SL
Enumeration Type Documentation
anonymous enum
Enumerator:
set_none
set_any
set_regular
set_whitespace
Function Documentation
char* check_set (char * annot)
References cl_free, cl_make_set(), set_any, set_att, set_none, set_regular, set_syntax_strict, and set_whitespace.
Referenced by main().
void close_range (void)
References Range::avs, Range::avx, Range::fd, and Range::ready.
void declare_range (char * name, char * directory, int store_values)
References Range::avs, Range::avx, cl_strdup(), Range::dir, Range::fd, Range::last_cpos, Range::name, Range::num, Range::offset, Range::ready, and Range::store_values.
int main (int argc, char ** argv)
Main function for cwb-s-encode.
Parameters:
argc Number of command-line arguments.
argv Command-line arguments.
References add_to_existing, _SL::annot, ATT_STRUC, buf, check_set(), cl_free, cl_max_struc(), cl_new_attribute, cl_struc2cpos, cl_struc2str, cl_struc_values, close_range(), debug, _SL::end, in_memory, input_line, Range::last_cpos, MAX_LINE_LENGTH, Range::name, parse_line(), parse_options(), progname, set_att, set_none, silent, SL_insert(), SL_next(), SL_rewind(), _SL::start, Range::store_values, text_fd, and write_region_to_disk().
void open_range (void)
References Range::avs, Range::avx, buf, Range::dir, Range::fd, MAX_LINE_LENGTH, Range::name, Range::ready, RNG_AVS, RNG_AVX, RNG_RNG, and Range::store_values.
int parse_line (char * line, int * start, int * end, char ** annot)
References cl_free, and cl_strdup().
Referenced by main().
void parse_options (int argc, char ** argv)
Parses program options and sets global variables.
Parameters:
argc argc - passed from main()
argv argv - passed from main()
References add_to_existing, cl_new_corpus, debug, declare_range(), directory, in_memory, Range::name, registry, set_any, set_att, set_syntax_strict, silent, strip_blanks_in_values, text_fd, and usage().
void SL_delete (SL item)
References _SL::annot, cl_free, _SL::next, and _SL::prev.
Referenced by SL_insert().
void SL_insert (int start, int end, char * annot)
References _SL::end, _SL::next, SL_delete(), SL_insert_after_point(), SL_seek(), and _SL::start.
Referenced by main().
SL SL_insert_after_point (int start, int end, char * annot)
References _SL::annot, cl_malloc(), cl_strdup(), _SL::end, _SL::next, _SL::prev, and _SL::start.
Referenced by SL_insert().
SL SL_next (void)
References _SL::next.
Referenced by main().
void SL_rewind (void)
Referenced by main().
SL SL_seek (int cpos)
References _SL::end, _SL::next, _SL::prev, and _SL::start.
Referenced by SL_insert().
void usage (void)
References progname.
void write_region_to_disk (int start, int end, char * annot)
References Range::avs, Range::avx, cl_lexhash_add(), cl_lexhash_find(), cl_new_lexhash(), _cl_lexhash_entry::data, Range::fd, _cl_lexhash_entry::id, _cl_lexhash_entry_data::integer, Range::last_cpos, Range::num, NwriteInt(), Range::offset, open_range(), Range::ready, and Range::store_values.
Referenced by main().
Variable Documentation
int add_to_existing = 0
Referenced by main(), and parse_options().
Corpus* corpus = NULL
int debug = 0
int in_memory = 0
Referenced by main(), and parse_options().
cl_lexhash LH = NULL
int line = 0
char* progname = NULL
Range range
Referenced by get_matched_corpus_positions(), get_positions(), matchfirstpattern(), OpenPositionStream(), OptimizeStringConstraint(), and show_subcorpus_info().
enum { ... } set_att
Referenced by check_set(), main(), and parse_options().
int set_syntax_strict = 0
Referenced by check_set(), and parse_options().
int silent = 0
SL SL_Point = NULL
int strip_blanks_in_values = 0
Referenced by parse_options().
SL StructureList = NULL
FILE* text_fd = NULL
Referenced by main(), and parse_options().