CWB: utils/cwb-atoi.c File Reference
cwb-atoi.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include "../cl/endian.h"
Defines
#define MAX_LINE_LENGTH 1024
Functions
void process_fd (FILE *fd)
Reads from a stream one integer-representing string per line, and writes the corresponding integer to STDOUT.
int main (int argc, char **argv)
Main function for cwb-atoi.
Variables
int little_endian = 0
boolean: is the byte-order little-endian?
Define Documentation
#define MAX_LINE_LENGTH 1024
Function Documentation
int main (int argc, char ** argv)
Main function for cwb-atoi.
Parameters:
argc Number of command-line arguments.
argv Command-line arguments.
References little_endian, process_fd(), and progname.
void process_fd (FILE * fd)
Reads from a stream one integer-representing string per line, and writes the corresponding integer to STDOUT.
Parameters:
fd The file handle.
References buf, cl_bswap32(), little_endian, and MAX_LINE_LENGTH.
Referenced by main().
Variable Documentation
int little_endian = 0
boolean: is the byte-order little-endian?
CWB default format is 4-byte big-endian = network
Referenced by main(), and process_fd().