CWB: cqp/groups.c File Reference
groups.c File Reference
#include "../cl/globals.h"
#include <math.h>
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include "../cl/macros.h"
#include "../cl/binsert.h"
#include "options.h"
#include "html-print.h"
#include "ascii-print.h"
#include "sgml-print.h"
#include "latex-print.h"
#include "corpmanag.h"
#include "groups.h"
#include "output.h"
Defines
#define SEPARATOR "#---------------------------------------------------------------------\n"
#define SEPARATOR2 "#=====================================================================\n"
#define GROUP_DEBUG 0
#define ANY_ID -2
#define GROUP_REALLOC 16
Functions
static int compare_by_freq (const void *p1, const void *p2)
int sum_freqs (ID_Count_Mapping *buffer, int bufsize, int cutoff_f)
static int compare_st_cells (const void *p1, const void *p2)
int get_group_id (Group *group, int i, int target)
char * Group_id2str (Group *group, int id, int target)
Group * ComputeGroupInternally (Group *group)
Group * ComputeGroupExternally (Group *group)
Group * compute_grouping (CorpusList *cl, FieldType source_field, int source_offset, char *source_attr_name, FieldType target_field, int target_offset, char *target_attr_name, int cutoff_freq)
void free_group (Group **group)
void print_group (Group *group, int expand, struct Redir *rd)
Define Documentation
#define ANY_ID -2
Referenced by get_group_id(), and Group_id2str().
#define GROUP_DEBUG 0
Referenced by ComputeGroupExternally().
#define GROUP_REALLOC 16
Referenced by ComputeGroupExternally().
#define SEPARATOR "#---------------------------------------------------------------------\n"
Referenced by ascii_print_group().
#define SEPARATOR2 "#=====================================================================\n"
Function Documentation
static int compare_by_freq (const void * p1, const void * p2) [static]
Referenced by sum_freqs().
static int compare_st_cells (const void * p1, const void * p2) [static]
Referenced by ComputeGroupInternally().
Group* compute_grouping (CorpusList * cl, FieldType source_field, int source_offset, char * source_attr_name, FieldType target_field, int target_offset, char * target_attr_name, int cutoff_freq)
References ATT_POS, ATT_STRUC, cl_malloc(), cl_struc2str, cl_struc_values, ComputeGroupExternally(), ComputeGroupInternally(), cl::corpus, _grouptable::count_cells, cqpmessage(), _grouptable::cutoff_frequency, Error, find_attribute(), insecure, KeywordField, cl::keywords, MatchEndField, MatchField, _grouptable::my_corpus, cl::name, NoField, _grouptable::nr_cells, cl::range, cl::size, _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_field, _grouptable::source_is_struc, _grouptable::source_offset, _grouptable::target_attribute, _grouptable::target_base, _grouptable::target_field, _grouptable::target_is_struc, _grouptable::target_offset, TargetField, cl::targets, UseExternalGrouping, and Warning.
Referenced by do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_group(), and do_group2().
Group* ComputeGroupExternally (Group * group)
References cl_malloc(), cl_realloc(), _grouptable::count_cells, cqpmessage(), _grouptable::cutoff_frequency, ExternalGroupingCommand, _id_cnt_mapping::freq, get_group_id(), GROUP_DEBUG, GROUP_REALLOC, _grouptable::my_corpus, _grouptable::nr_cells, OpenTemporaryFile(), _id_cnt_mapping::s, cl::size, _id_cnt_mapping::t, and Warning.
Referenced by compute_grouping().
Group* ComputeGroupInternally (Group * group)
References binsert_g(), cl_realloc(), compare_st_cells(), _grouptable::count_cells, cqp, cqpmessage(), _grouptable::cutoff_frequency, EvaluationIsRunning, free_group(), _id_cnt_mapping::freq, get_group_id(), install_signal_handler(), _grouptable::my_corpus, node, _grouptable::nr_cells, progress_bar, progress_bar_clear_line(), progress_bar_percentage(), _id_cnt_mapping::s, cl::size, sum_freqs(), _id_cnt_mapping::t, Warning, and which_app.
Referenced by compute_grouping().
void free_group (Group ** group)
References cl_free.
Referenced by ComputeGroupInternally(), do_cqi_cqp_fdist_1(), do_cqi_cqp_fdist_2(), do_group(), and do_group2().
int get_group_id (Group * group, int i, int target)
References ANY_ID, cl_cpos2id, cl_cpos2struc2str, KeywordField, cl::keywords, MatchEndField, MatchField, _grouptable::my_corpus, NoField, cl::range, _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_field, _grouptable::source_is_struc, _grouptable::source_offset, _grouptable::target_attribute, _grouptable::target_base, _grouptable::target_field, _grouptable::target_is_struc, _grouptable::target_offset, TargetField, and cl::targets.
Referenced by ComputeGroupExternally(), and ComputeGroupInternally().
char* Group_id2str (Group * group, int id, int target)
References ANY_ID, cl_id2str, _grouptable::source_attribute, _grouptable::source_base, _grouptable::source_is_struc, _grouptable::target_attribute, _grouptable::target_base, and _grouptable::target_is_struc.
Referenced by ascii_print_group(), html_print_group(), latex_print_group(), and sgml_print_group().
void print_group (Group * group, int expand, struct Redir * rd)
References ascii_print_group(), TCorpus::charset, close_stream(), cl::corpus, cqpmessage(), Error, GlobalPrintMode, html_print_group(), latex_print_group(), _grouptable::my_corpus, open_stream(), PrintASCII, PrintHTML, PrintLATEX, PrintSGML, sgml_print_group(), and Redir::stream.
Referenced by do_group(), and do_group2().
int sum_freqs (ID_Count_Mapping * buffer, int bufsize, int cutoff_f)
References compare_by_freq(), _id_cnt_mapping::freq, progress_bar, progress_bar_message(), progress_bar_percentage(), _id_cnt_mapping::s, and _id_cnt_mapping::t.
Referenced by ComputeGroupInternally().