CWB: cl/makecomps.h File Reference
makecomps.h File Reference
#include "globals.h"
#include "attributes.h"
Functions
int creat_sort_lexicon (Component *lexsrt)
creates a sort index.
int creat_freqs (Component *lex)
creates frequency table
int creat_rev_corpus (Component *component)
creates reversed corpus
int creat_rev_corpus_idx (Component *component)
creates index for reversed corpus
Function Documentation
int creat_freqs (Component * freqs)
creates frequency table
See also:
create_component
References TComponent::attribute, BUFSIZE, CompCorpus, CompCorpusFreqs, CompLexiconIdx, component_full_name(), TMblob::data, TComponent::data, ensure_component(), find_component(), TComponent::id, MALLOCED, TComponent::path, read_file_into_blob(), TComponent::size, TMblob::size, and write_file_from_blob().
Referenced by create_component().
int creat_rev_corpus (Component * revcorp)
creates reversed corpus
See also:
create_component
References TComponent::attribute, cl_cpos2id, cl_debug, cl_free, cl_id2freq, cl_malloc(), cl_max_cpos, cl_max_id, cl_memory_limit, CompCorpusFreqs, TComponent::corpus, TMblob::data, TComponent::data, ensure_component(), NwriteInt(), NwriteInts(), and TComponent::path.
Referenced by create_component().
int creat_rev_corpus_idx (Component * revcidx)
creates index for reversed corpus
See also:
create_component
References TMblob::allocation_method, TComponent::attribute, TMblob::changed, cl_malloc(), CompCorpusFreqs, TComponent::corpus, TMblob::data, TComponent::data, ensure_component(), TMblob::fname, TMblob::fsize, TMblob::item_size, MALLOCED, TMblob::nr_items, TMblob::offset, TComponent::path, TComponent::size, TMblob::size, SIZE_INT, write_file_from_blob(), and TMblob::writeable.
Referenced by create_component().
int creat_sort_lexicon (Component * lexsrt)
creates a sort index.
See also:
create_component
References TComponent::attribute, comp_component_state(), CompLexicon, CompLexiconIdx, ComponentDefined, TMblob::data, TComponent::data, ensure_component(), TMblob::item_size, MALLOCED, TMblob::nr_items, TComponent::path, read_file_into_blob(), scompare(), TComponent::size, TMblob::size, and write_file_from_blob().
Referenced by create_component().