CWB: cqp/matchlist.c File Reference
matchlist.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include "../cl/macros.h"
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include "matchlist.h"
#include "output.h"
#include "eval.h"
Functions
void init_matchlist (Matchlist *matchlist)
void show_matchlist (Matchlist matchlist)
void show_matchlist_firstelements (Matchlist matchlist)
void free_matchlist (Matchlist *matchlist)
int Setop (Matchlist *list1, MLSetOp operation, Matchlist *list2)
Function Documentation
void free_matchlist (Matchlist * matchlist)
References cl_free, _Matchlist::end, init_matchlist(), _Matchlist::start, and _Matchlist::target_positions.
Referenced by calculate_initial_matchlist_1(), check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), Setop(), simulate(), simulate_dfa(), and try_optimization().
void init_matchlist (Matchlist * matchlist)
References _Matchlist::end, _Matchlist::is_inverted, _Matchlist::matches_whole_corpus, _Matchlist::start, _Matchlist::tabsize, and _Matchlist::target_positions.
Referenced by calculate_initial_matchlist_1(), check_alignment_constraints(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), free_matchlist(), simulate_dfa(), and try_optimization().
int Setop (Matchlist * list1, MLSetOp operation, Matchlist * list2)
References access_corpus(), ATT_POS, CDA_OK, cderrno, cl_free, cl_malloc(), cl_realloc(), Complement, DEFAULT_ATT_NAME, _Matchlist::end, find_attribute(), free_matchlist(), get_attribute_size(), Identity, Intersection, _Matchlist::is_inverted, _Matchlist::matches_whole_corpus, MIN, Reduce, Setop(), _Matchlist::start, _Matchlist::tabsize, _Matchlist::target_positions, Union, and Uniq.
Referenced by calculate_initial_matchlist(), calculate_initial_matchlist_1(), cqp_run_mu_query(), cqp_run_tab_query(), eval_mu_tree(), matchfirstpattern(), Setop(), simulate_dfa(), and try_optimization().
void show_matchlist (Matchlist matchlist)
References _Matchlist::end, _Matchlist::is_inverted, _Matchlist::start, _Matchlist::tabsize, and _Matchlist::target_positions.
Referenced by simulate_dfa().
void show_matchlist_firstelements (Matchlist matchlist)
References _Matchlist::start, and _Matchlist::tabsize.
Referenced by simulate_dfa().