CWB: cqp/output.c File Reference
output.c File Reference
#include <stdio.h>
#include <string.h>
#include <signal.h>
#include <stdarg.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/time.h>
#include "../cl/cl.h"
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include "concordance.h"
#include "cqp.h"
#include "options.h"
#include "output.h"
#include "corpmanag.h"
#include "print-modes.h"
#include "print_align.h"
#include "ascii-print.h"
#include "sgml-print.h"
#include "html-print.h"
#include "latex-print.h"
#include <sys/types.h>
#include <pwd.h>
Functions
void print_corpus_info_header (CorpusList *cl, FILE *stream, PrintMode mode, int force)
FILE * OpenTemporaryFile (char *tmp_name_buffer)
FILE * OpenFile (char *name, char *mode)
FILE * open_pager (char *cmd, CorpusCharset charset)
int open_stream (struct Redir *rd, CorpusCharset charset)
int close_stream (struct Redir *rd)
int open_input_stream (struct InputRedir *rd)
int close_input_stream (struct InputRedir *rd)
static void bp_signal_handler (int signum)
void print_output (CorpusList *cl, FILE *fd, int interactive, ContextDescriptor *cd, int first, int last, PrintMode mode)
void catalog_corpus (CorpusList *cl, struct Redir *rd, int first, int last, PrintMode mode)
void cqpmessage (MessageType type, char *format,...)
void corpus_info (CorpusList *cl)
void free_tabulation_list (void)
TabulationItem new_tabulation_item (void)
void append_tabulation_item (TabulationItem item)
int pt_get_anchor_cpos (CorpusList *cl, int n, FieldType anchor, int offset)
int pt_validate_anchor (CorpusList *cl, FieldType anchor)
int print_tabulation (CorpusList *cl, int first, int last, struct Redir *rd)
Variables
TabulationItem TabulationList = NULL
int broken_pipe
Function Documentation
void append_tabulation_item (TabulationItem item)
References _TabulationItem::next.
static void bp_signal_handler (int signum) [static]
References broken_pipe.
Referenced by catalog_corpus().
void catalog_corpus (CorpusList * cl, struct Redir * rd, int first, int last, PrintMode mode)
References access_corpus(), bp_signal_handler(), broken_pipe, CD, TCorpus::charset, close_stream(), cl::corpus, cqpmessage(), Error, False, GlobalPrintMode, GlobalPrintOptions, handle_sigpipe, Redir::is_paging, Redir::is_pipe, Redir::mode, Redir::name, open_stream(), print_corpus_info_header(), _print_option_rec_::print_header, print_output(), PrintASCII, PrintBINARY, PrintHTML, printNrMatches, cl::range, rangeoutput, cl::size, Redir::stream, True, and verify_context_descriptor().
Referenced by after_CorpusCommand(), and do_cat().
int close_input_stream (struct InputRedir * rd)
References InputRedir::is_pipe, and InputRedir::stream.
Referenced by do_undump().
int close_stream (struct Redir * rd)
References Redir::is_pipe, and Redir::stream.
Referenced by catalog_corpus(), corpus_info(), do_dump(), print_group(), print_tabulation(), PrintContextDescriptor(), and SortSubcorpus().
void corpus_info (CorpusList * cl)
References ascii, buf, TCorpus::charset, cl_charset_name(), cl_corpus_property(), cl_first_corpus_property(), cl_next_corpus_property(), close_stream(), cl::corpus, corpus_info(), cqpmessage(), findcorpus(), Info, TCorpus::info_file, cl::mother_name, cl::mother_size, cl::name, open_stream(), OpenFile(), TCorpusProperty::property, Redir::stream, SYSTEM, cl::type, unknown_charset, TCorpusProperty::value, and Warning.
Referenced by corpus_info(), and do_info().
void cqpmessage (MessageType type, char * format, ...)
References Error, Info, Message, silent, verbose_parser, and Warning.
Referenced by ActivateCorpus(), add_host_to_list(), add_hosts_in_subnet_to_list(), add_user_to_list(), addHistoryLine(), after_CorpusSetExpr(), attach_subcorpus(), calculate_initial_matchlist_1(), call_predefined_function(), catalog_corpus(), check_alignment_constraints(), check_labels(), compute_grouping(), ComputeGroupExternally(), ComputeGroupInternally(), ComputePrintStructures(), copy_intervals(), corpus_info(), cqp_parse_string(), cqp_run_mu_query(), define_macro(), do_AddSubVariables(), do_AnchorPoint(), do_attribute_show(), do_cat(), do_cut(), do_delete_lines(), do_delete_lines_num(), do_Description(), do_dump(), do_exec(), do_flagged_re_variable(), do_flagged_string(), do_IDReference(), do_LabelReference(), do_MUQuery(), do_mval_string(), do_NamedWfPattern(), do_OptDistance(), do_printVariableSize(), do_PrintVariableValue(), do_reduce(), do_RelExpr(), do_save(), do_SearchPattern(), do_setop(), do_SetVariableValue(), do_SimpleVariableReference(), do_StandardQuery(), do_StringConstraint(), do_StructuralContext(), do_timing(), do_undump(), do_WordformPattern(), do_XMLTag(), duplicate_corpus(), ensure_corpus_size(), eval_bool(), evaluate_subset(), evaluate_target(), execute_side_effects(), expand_dataspace(), expand_macro(), field_type_to_name(), findcorpus(), FunctionCall(), get_leaf_value(), in_CorpusCommand(), in_UnnamedCorpusCommand(), init_macros(), initialize_cqp(), install_signal_handler(), load_corpusnames(), load_macro_file(), MacroHashAdd(), MacroHashDelete(), MacroHashLookup(), matchfirstpattern(), mval_string_conversion(), open_stream(), OptimizeStringConstraint(), prepare_AlignmentConstraints(), prepare_do_subset(), prepare_parse(), prepare_Query(), print_concordance_line(), print_group(), print_macro_definition(), print_output(), print_tabulation(), pt_validate_anchor(), push_regchr(), RangeSort(), save_subcorpus(), save_unsaved_subcorpora(), set_reftab(), set_target(), SetVariableValue(), simulate(), simulate_dfa(), SortExternally(), SortSubcorpus(), SortSubcorpusRandomize(), string_to_strategy(), Varref2IDList(), verify_context_descriptor(), and yy_input_char().
void free_tabulation_list (void)
References _TabulationItem::attribute_name, cl_free, and _TabulationItem::next.
Referenced by print_tabulation().
TabulationItem new_tabulation_item (void)
References _TabulationItem::anchor1, _TabulationItem::anchor2, ATT_NONE, _TabulationItem::attribute, _TabulationItem::attribute_name, _TabulationItem::attribute_type, cl_malloc(), _TabulationItem::flags, _TabulationItem::next, NoField, _TabulationItem::offset1, and _TabulationItem::offset2.
int open_input_stream (struct InputRedir * rd)
References cl_free, cl_malloc(), False, insecure, InputRedir::is_pipe, InputRedir::name, OpenFile(), InputRedir::stream, and True.
Referenced by do_undump().
FILE* open_pager (char * cmd, CorpusCharset charset)
References ascii, cl_strdup(), less_charset_variable, tested_pager, and utf8.
Referenced by open_stream().
int open_stream (struct Redir * rd, CorpusCharset charset)
References cl_strdup(), CQP_FALLBACK_PAGER, cqpmessage(), Error, False, insecure, Redir::is_paging, Redir::is_pipe, Redir::mode, Redir::name, open_pager(), OpenFile(), pager, paging, set_integer_option_value(), set_string_option_value(), Redir::stream, True, and Warning.
Referenced by catalog_corpus(), corpus_info(), do_dump(), print_group(), print_tabulation(), PrintContextDescriptor(), and SortSubcorpus().
FILE* OpenFile (char * name, char * mode)
Referenced by addHistoryLine(), attach_subcorpus(), check_stamp(), corpus_info(), do_exec(), open_input_stream(), open_stream(), parse_options(), save_subcorpus(), and SetVariableValue().
FILE* OpenTemporaryFile (char * tmp_name_buffer)
Referenced by ComputeGroupExternally(), and SortExternally().
void print_corpus_info_header (CorpusList * cl, FILE * stream, PrintMode mode, int force)
References ascii_print_corpus_header(), GlobalPrintOptions, html_print_corpus_header(), latex_print_corpus_header(), _print_option_rec_::print_header, PrintASCII, PrintHTML, PrintLATEX, PrintSGML, and sgml_print_corpus_header().
Referenced by catalog_corpus().
void print_output (CorpusList * cl, FILE * fd, int interactive, ContextDescriptor * cd, int first, int last, PrintMode mode)
References ascii_print_output(), cqpmessage(), Error, html_print_output(), latex_print_output(), PrintASCII, PrintHTML, PrintLATEX, PrintSGML, and sgml_print_output().
Referenced by catalog_corpus().
int print_tabulation (CorpusList * cl, int first, int last, struct Redir * rd)
References _TabulationItem::anchor1, _TabulationItem::anchor2, ATT_NONE, ATT_POS, ATT_STRUC, _TabulationItem::attribute, _TabulationItem::attribute_name, _TabulationItem::attribute_type, TCorpus::charset, cl_cpos2str, cl_cpos2struc2str, cl_free, cl_new_attribute, cl_strdup(), cl_string_canonical(), cl_struc_values, close_stream(), cl::corpus, cqpmessage(), Error, _TabulationItem::flags, free_tabulation_list(), cl::name, _TabulationItem::next, _TabulationItem::offset1, _TabulationItem::offset2, open_stream(), pt_get_anchor_cpos(), pt_validate_anchor(), cl::size, and Redir::stream.
int pt_get_anchor_cpos (CorpusList * cl, int n, FieldType anchor, int offset)
References KeywordField, cl::keywords, MatchEndField, MatchField, cl::mother_size, NoField, cl::range, cl::sortidx, TargetField, and cl::targets.
Referenced by print_tabulation().
int pt_validate_anchor (CorpusList * cl, FieldType anchor)
References cqpmessage(), Error, KeywordField, cl::keywords, MatchEndField, MatchField, cl::name, NoField, cl::range, cl::size, TargetField, and cl::targets.
Referenced by print_tabulation().
Variable Documentation
int broken_pipe
Referenced by ascii_print_output(), bp_signal_handler(), catalog_corpus(), html_print_output(), latex_print_output(), and sgml_print_output().
TabulationItem TabulationList = NULL