CWB: cqp/print-modes.c File Reference
print-modes.c File Reference
#include <stdio.h>
#include <string.h>
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include "corpmanag.h"
#include "attlist.h"
#include "output.h"
#include "options.h"
Defines
#define PRINT_STRUC_SEP ": ,"
String containing print structure separators.
Functions
AttributeList * ComputePrintStructures (CorpusList *cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
void ResetPrintOptions (void)
This function doesn't do anything yet.
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
void CopyPrintOptions (PrintOptions *target, PrintOptions *source)
Copies a PrintOptions object.
Variables
PrintMode GlobalPrintMode = PrintASCII
Global print-mode setting.
PrintOptions GlobalPrintOptions = { 0, 0, 0, 0, 0 }
Global print-options: all booleans initially set to false.
Define Documentation
#define PRINT_STRUC_SEP ": ,"
String containing print structure separators.
Referenced by ComputePrintStructures().
Function Documentation
AttributeList* ComputePrintStructures (CorpusList * cl)
Computes a list of s-attributes to print from the PrintStructure global option setting.
PrintStructure is itself updated.
Parameters:
cl The corpus from which to find the attributes.
Returns:
An attribute list containing the attributes to be printed.
References AddNameToAL(), _Attribute::any, ATT_STRUC, _attrbuf::attribute, cl::corpus, cqpmessage(), DestroyAttributeList(), Error, find_attribute(), _attlist::list, NewAttributeList(), _attrbuf::next, PRINT_STRUC_SEP, printStructure, TCorpus::registry_name, structure_has_values(), VerifyList(), and Warning.
Referenced by execute_side_effects().
void CopyPrintOptions (PrintOptions * target, PrintOptions * source)
Copies a PrintOptions object.
Parameters:
target The PrintOptions object to be overwritten.
source The PrintOptions object to copy.
void ParsePrintOptions (void)
Reads the global string printModeOptions and parses it to update the GlobalPrintOptions.
See also:
printModeOptions
GlobalPrintOptions
References _print_option_rec_::number_lines, _print_option_rec_::print_border, _print_option_rec_::print_header, _print_option_rec_::print_tabular, _print_option_rec_::print_wrap, printModeOptions, and silent.
Referenced by execute_side_effects(), html_print_output(), and latex_print_output().
void ResetPrintOptions (void)
This function doesn't do anything yet.
Variable Documentation
PrintMode GlobalPrintMode = PrintASCII
Global print-mode setting.
Referenced by after_CorpusCommand(), catalog_corpus(), do_cat(), execute_side_effects(), print_group(), and printAlignedStrings().
PrintOptions GlobalPrintOptions = { 0, 0, 0, 0, 0 }
Global print-options: all booleans initially set to false.
Referenced by ascii_print_output(), catalog_corpus(), html_print_aligned_line(), html_print_corpus_header(), html_print_field(), html_print_output(), latex_print_field(), latex_print_output(), print_corpus_info_header(), and print_option_value().