CWB: cqp/ranges.h File Reference
ranges.h File Reference
#include "eval.h"
#include "corpmanag.h"
#include "output.h"
#include "../cl/bitfields.h"
#include "../cl/attributes.h"
Data Structures
struct _sort_clause
Defines
#define SORT_FROM_START 0
#define SORT_FROM_END 1
#define SORT_RESET 2
#define ALL_LINES 1
#define SELECTED_LINES 2
#define UNSELECTED_LINES 3
Typedefs
typedef struct _sort_clause SortClauseBuffer
typedef struct _sort_clause * SortClause
typedef enum rng_setops RangeSetOp
Enumerations
enum rng_setops {
RUnion, RIntersection, RDiff, RMaximalMatches,
RMinimalMatches, RLeftMaximalMatches, RNonOverlapping, RUniq,
RReduce
}
Functions
Boolean delete_interval (CorpusList *cp, int interval_number)
Boolean delete_intervals (CorpusList *cp, Bitfield which_intervals, int mode)
Boolean copy_intervals (CorpusList *cp, Bitfield which_intervals, int mode, char *subcorpname)
Boolean calculate_ranges (CorpusList *cl, int cpos, Context spc, int *left, int *right)
int calculate_rightboundary (CorpusList *cl, int cpos, Context spc)
int calculate_leftboundary (CorpusList *cl, int cpos, Context spc)
int RangeSetop (CorpusList *list1, RangeSetOp operation, CorpusList *list2, Bitfield restrictor)
void RangeSort (CorpusList *c, int mk_sortidx)
int SortSubcorpus (CorpusList *cl, SortClause sc, int count_mode, struct Redir *redir)
int SortSubcorpusRandomize (CorpusList *cl, int seed)
void FreeSortClause (SortClause sc)
Define Documentation
#define ALL_LINES 1
Referenced by delete_intervals().
#define SELECTED_LINES 2
Referenced by copy_intervals(), delete_intervals(), and do_delete_lines_num().
#define SORT_FROM_END 1
#define SORT_FROM_START 0
#define SORT_RESET 2
#define UNSELECTED_LINES 3
Referenced by copy_intervals(), delete_intervals(), do_reduce(), and do_StandardQuery().
Typedef Documentation
typedef enum rng_setops RangeSetOp
typedef struct _sort_clause * SortClause
typedef struct _sort_clause SortClauseBuffer
Enumeration Type Documentation
enum rng_setops
Enumerator:
RUnion
RIntersection
RDiff
RMaximalMatches
RMinimalMatches
RLeftMaximalMatches
RNonOverlapping
RUniq
RReduce
Function Documentation
int calculate_leftboundary (CorpusList * cl, int cpos, Context spc)
References calculate_ranges(), left, and right.
Referenced by expand_dataspace(), and findcorpus().
Boolean calculate_ranges (CorpusList * cl, int cpos, Context spc, int * left, int * right)
References ctxtsp::attrib, False, get_bounds_of_nth_struc(), get_nr_of_strucs(), get_num_of_struc(), get_struc_attribute(), MAX, MIN, cl::mother_size, ctxtsp::size, structure, True, ctxtsp::type, and word.
Referenced by calculate_leftboundary(), calculate_rightboundary(), and evaluate_target().
int calculate_rightboundary (CorpusList * cl, int cpos, Context spc)
References calculate_ranges(), left, and right.
Referenced by expand_dataspace(), findcorpus(), and simulate().
Boolean copy_intervals (CorpusList * cp, Bitfield which_intervals, int mode, char * subcorpname)
References auto_save, cqpmessage(), delete_intervals(), dropcorpus(), duplicate_corpus(), BFBuf::elements, Error, False, findcorpus(), cl::mother_name, cl::name, RangeSetop(), RUnion, save_subcorpus(), cl::saved, SELECTED_LINES, cl::size, SUB, SYSTEM, toggle_bit(), cl::type, UNDEF, and UNSELECTED_LINES.
Boolean delete_interval (CorpusList * cp, int interval_number)
References cl_free, False, cl::range, RangeSetop(), RReduce, cl::size, cl::sortidx, SUB, and cl::type.
Boolean delete_intervals (CorpusList * cp, Bitfield which_intervals, int mode)
References ALL_LINES, auto_save, cl_free, BFBuf::elements, False, get_bit(), cl::keywords, cl::range, RangeSetop(), RReduce, save_subcorpus(), SELECTED_LINES, cl::size, cl::sortidx, SUB, cl::targets, TEMP, touch_corpus(), True, cl::type, and UNSELECTED_LINES.
Referenced by copy_intervals(), do_delete_lines(), do_delete_lines_num(), do_reduce(), and do_StandardQuery().
void FreeSortClause (SortClause sc)
References _sort_clause::attribute_name, and cl_free.
int RangeSetop (CorpusList * list1, RangeSetOp operation, CorpusList * list2, Bitfield restrictor)
References cl_free, cl_malloc(), cl_realloc(), get_bit(), cl::keywords, cl::range, RangeSetop(), RDiff, RIntersection, RLeftMaximalMatches, RMaximalMatches, RMinimalMatches, RNonOverlapping, RReduce, rs_cp_range(), RUnion, RUniq, cl::size, cl::sortidx, cl::targets, and touch_corpus().
Referenced by copy_intervals(), delete_interval(), delete_intervals(), do_cut(), do_setop(), do_StandardQuery(), evaluate_subset(), expand_dataspace(), findcorpus(), prepare_Query(), RangeSetop(), and set_corpus_matchlists().
void RangeSort (CorpusList * c, int mk_sortidx)
References _RS_compare_ranges(), cl_free, cl_malloc(), cqpmessage(), Error, cl::keywords, cl::name, cl::range, cl::size, cl::sortidx, SUB, cl::targets, TEMP, cl::type, and Warning.
Referenced by do_undump(), evaluate_target(), and set_target().
int SortSubcorpus (CorpusList * cl, SortClause sc, int count_mode, struct Redir * redir)
References access_corpus(), _sort_clause::anchor1, _sort_clause::anchor2, ATT_POS, _sort_clause::attribute_name, break_ties, TCorpus::charset, cl_cpos2id, cl_cpos2str, cl_free, cl_malloc(), cl_max_cpos, cl_strdup(), cl_string_canonical(), cl_string_maptable(), close_stream(), cl::corpus, cqp, cqpmessage(), current_sortidx, DEFAULT_ATT_NAME, Error, EvaluationIsRunning, find_attribute(), _sort_clause::flags, group2compare(), group_first, group_size, i2compare(), Info, insecure, install_signal_handler(), KeywordField, cl::keywords, latin1, MatchEndField, MatchField, cl::name, NoField, _sort_clause::offset1, _sort_clause::offset2, open_stream(), pretty_print, cl::range, cl::size, _sort_clause::sort_ascending, sort_id_cache, _sort_clause::sort_reverse, SortExternally(), cl::sortidx, srt_anchor1, srt_anchor2, srt_ascending, srt_end, srt_maptable, srt_offset1, srt_offset2, srt_reverse, srt_start, Redir::stream, TargetField, cl::targets, text_size, touch_corpus(), USE_SORT_CACHE, UseExternalSorting, Warning, and which_app.
int SortSubcorpusRandomize (CorpusList * cl, int seed)
References access_corpus(), cl_free, cl_malloc(), cl_random(), cl_set_rng_state(), cqp, cqpmessage(), Error, EvaluationIsRunning, Info, install_signal_handler(), cl::name, random_compare(), random_sort_keys, cl::range, cl::size, cl::sortidx, touch_corpus(), Warning, and which_app.