CWB: cqp/variables.c File Reference
variables.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include "../cl/corpus.h"
#include "../cl/attributes.h"
#include "../cl/cdaccess.h"
#include "../cl/macros.h"
#include "variables.h"
#include "output.h"
Defines
#define ITEM_REALLOC 8
#define VARIABLE_REALLOC 16
Functions
Variable FindVariable (char *varname)
int VariableItemMember (Variable v, char *item)
int VariableAddItem (Variable v, char *item)
int VariableSubtractItem (Variable v, char *item)
int VariableDeleteItems (Variable v)
int DropVariable (Variable *vp)
Variable NewVariable (char *varname)
int SetVariableValue (char *varName, char operator, char *varValues)
void variables_iterator_new (void)
Variable variables_iterator_next (void)
int VerifyVariable (Variable v, Corpus *corpus, Attribute *attribute)
static int intcompare (const void *i, const void *j)
int * GetVariableItems (Variable v, Corpus *corpus, Attribute *attribute, int *nr_items)
char ** GetVariableStrings (Variable v, int *nr_items)
Variables
int nr_variables = 0
Variable * VariableSpace = NULL
int variables_iterator_idx
Define Documentation
#define ITEM_REALLOC 8
Referenced by VariableAddItem().
#define VARIABLE_REALLOC 16
Referenced by NewVariable().
Function Documentation
int DropVariable (Variable * vp)
References cl_free, _variable_buf::my_attribute, _variable_buf::my_corpus, _variable_buf::my_name, nr_variables, and VariableDeleteItems().
Variable FindVariable (char * varname)
References nr_variables.
Referenced by do_AddSubVariables(), do_flagged_re_variable(), do_printVariableSize(), do_PrintVariableValue(), do_SetVariableValue(), SetVariableValue(), and Varref2IDList().
int* GetVariableItems (Variable v, Corpus * corpus, Attribute * attribute, int * nr_items)
References cl_malloc(), _variable_item::free, intcompare(), _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_buf::nr_valid_items, and VerifyVariable().
Referenced by Varref2IDList().
char** GetVariableStrings (Variable v, int * nr_items)
References cl_malloc(), _variable_item::free, _variable_buf::items, _variable_buf::nr_items, and _variable_item::sval.
Referenced by do_AddSubVariables(), and do_flagged_re_variable().
static int intcompare (const void * i, const void * j) [static]
Referenced by GetVariableItems().
Variable NewVariable (char * varname)
References cl_malloc(), cl_realloc(), cl_strdup(), _variable_buf::items, _variable_buf::my_attribute, _variable_buf::my_corpus, _variable_buf::my_name, _variable_buf::nr_items, nr_variables, _variable_buf::valid, and VARIABLE_REALLOC.
Referenced by do_SetVariableValue(), and SetVariableValue().
int SetVariableValue (char * varName, char operator, char * varValues)
References cqpmessage(), Error, FindVariable(), NewVariable(), OpenFile(), VariableAddItem(), VariableDeleteItems(), VariableSubtractItem(), and Warning.
Referenced by do_SetVariableValue().
int VariableAddItem (Variable v, char * item)
References cl_malloc(), cl_realloc(), cl_strdup(), _variable_item::free, ITEM_REALLOC, _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_item::sval, _variable_buf::valid, and VariableItemMember().
Referenced by do_AddSubVariables(), and SetVariableValue().
int VariableDeleteItems (Variable v)
References cl_free, _variable_buf::items, _variable_buf::nr_invalid_items, _variable_buf::nr_items, _variable_buf::nr_valid_items, and _variable_buf::valid.
Referenced by DropVariable(), and SetVariableValue().
int VariableItemMember (Variable v, char * item)
References _variable_item::free, _variable_buf::items, _variable_buf::nr_items, and _variable_item::sval.
Referenced by VariableAddItem().
void variables_iterator_new (void)
References variables_iterator_idx.
Referenced by do_PrintAllVariables().
Variable variables_iterator_next (void)
References nr_variables, and variables_iterator_idx.
Referenced by do_PrintAllVariables().
int VariableSubtractItem (Variable v, char * item)
References cl_free, _variable_item::free, _variable_buf::items, _variable_item::ival, _variable_buf::nr_items, _variable_item::sval, and _variable_buf::valid.
Referenced by do_AddSubVariables(), and SetVariableValue().
int VerifyVariable (Variable v, Corpus * corpus, Attribute * attribute)
References _Attribute::any, ATT_POS, cl_free, cl_strdup(), _variable_item::free, get_id_of_string(), _variable_buf::items, _variable_item::ival, _variable_buf::my_attribute, _variable_buf::my_corpus, _variable_buf::nr_invalid_items, _variable_buf::nr_items, _variable_buf::nr_valid_items, TCorpus::registry_name, _variable_item::sval, and _variable_buf::valid.
Referenced by GetVariableItems().
Variable Documentation
int nr_variables = 0
Referenced by DropVariable(), FindVariable(), NewVariable(), and variables_iterator_next().
int variables_iterator_idx
Referenced by variables_iterator_new(), and variables_iterator_next().
Variable* VariableSpace = NULL